xenon-middleware/xenon

- src/nl/esciencecenter/xenon/adaptors/generic/Location.java
- src/nl/esciencecenter/xenon/adaptors/ssh/SshAdaptor.java
- src/nl/esciencecenter/xenon/adaptors/ssh/SshFiles.java
- src/nl/esciencecenter/xenon/adaptors/ssh/SshJobs.java
- src/nl/esciencecenter/xenon/adaptors/ssh/SshLocation.java
- src/nl/esciencecenter/xenon/adaptors/ssh/SshMultiplexedSession.java
- test/src/nl/esciencecenter/xenon/adaptors/ssh/SSHLocationTest.java
Requesting code review and pull for #207.
> Use SSH config file in SSH adaptor (fixes #207)

- src/nl/esciencecenter/xenon/adaptors/local/LocalAdaptor.java
- src/nl/esciencecenter/xenon/adaptors/local/LocalFiles.java
- src/nl/esciencecenter/xenon/adaptors/local/LocalJobs.java
- test/src/nl/esciencecenter/xenon/adaptors/local/LocalAdaptorTest.java
- test/src/nl/esciencecenter/xenon/adaptors/local/LocalFileAdaptorTest.java
- test/src/nl/esciencecenter/xenon/adaptors/local/LocalJobTestConfig.java
Updated some test to reflect changes. Fixes #219
> Allows credentials in local scheduler. 

- src/nl/esciencecenter/xenon/adaptors/generic/Location.java
- src/nl/esciencecenter/xenon/adaptors/ssh/SshAdaptor.java
- test/src/nl/esciencecenter/xenon/adaptors/ssh/SSHLocationTest.java
> Missing SSH config gives warning unless requested (fix #261)

- src/main/java/nl/esciencecenter/xenon/adaptors/gridengine/GridEngineSchedulerConnection.java
- src/main/java/nl/esciencecenter/xenon/adaptors/scripting/ScriptingParser.java
- src/main/java/nl/esciencecenter/xenon/adaptors/slurm/SlurmSchedulerConnection.java
- src/main/java/nl/esciencecenter/xenon/adaptors/torque/TorqueSchedulerConnection.java
- src/main/java/nl/esciencecenter/xenon/adaptors/torque/TorqueXmlParser.java
- src/test/java/nl/esciencecenter/xenon/adaptors/scripting/ScriptingParserTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/slurm/SlurmJobScriptGeneratorTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/torque/TorqueSchedulerConnectionTest.java
Fixes #250. Other unit tests are now also being solved in branch fix-unittest.
> ScriptingParser produces job ID string

- src/main/java/nl/esciencecenter/xenon/adaptors/generic/Location.java
- src/main/java/nl/esciencecenter/xenon/adaptors/gridengine/GridEngineJobScriptGenerator.java
- src/main/java/nl/esciencecenter/xenon/adaptors/local/LocalUtils.java
- src/main/java/nl/esciencecenter/xenon/files/RelativePath.java
- src/test/java/nl/esciencecenter/xenon/adaptors/CredentialTestConfig.java
- src/test/java/nl/esciencecenter/xenon/adaptors/GenericCredentialsAdaptorTestParent.java
- src/test/java/nl/esciencecenter/xenon/adaptors/gridengine/GridEngineJobScriptGeneratorTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/local/LocalCredentialTestConfig.java
- src/test/java/nl/esciencecenter/xenon/adaptors/local/LocalUtilsTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/ssh/ITMultiJobTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/ssh/ITSSHTunnelTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/ssh/SSHCredentialTestConfig.java
- src/test/java/nl/esciencecenter/xenon/adaptors/torque/TorqueJobScriptGeneratorTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/torque/TorqueXmlParserTest.java
- src/test/java/nl/esciencecenter/xenon/engine/AdaptorStatusImplementationTest.java
- src/test/java/nl/esciencecenter/xenon/engine/AdaptorTest.java
- src/test/java/nl/esciencecenter/xenon/engine/XenonEngineTest.java
- src/test/java/nl/esciencecenter/xenon/engine/XenonPropertiesTest.java
- src/test/java/nl/esciencecenter/xenon/engine/files/PathImplementationTest.java
- src/test/java/nl/esciencecenter/xenon/files/ITInterSchemeCopyTest.java
- src/test/java/nl/esciencecenter/xenon/files/ITInterSchemeMoveTest.java
- src/test/java/nl/esciencecenter/xenon/files/RelativePathIteratorTest.java
- src/test/java/nl/esciencecenter/xenon/jobs/JobDescriptionTest.java
All unit tests now run successfully on my machine with `gradle test`. This operation involved moving some tests that actively need SSH to their `IT*Test.java` equivalent.
> Fixed unit tests

- .travis.yml
- README.md
- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshCredentials.java
- src/main/java/nl/esciencecenter/xenon/credentials/Credentials.java
- src/test/java/nl/esciencecenter/xenon/Util.java
- src/test/java/nl/esciencecenter/xenon/adaptors/GenericCredentialsAdaptorTestParent.java
- src/test/java/nl/esciencecenter/xenon/adaptors/ssh/ITSSHCredentialTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/ssh/SSHCredentialTest.java
- src/test/java/nl/esciencecenter/xenon/engine/credentials/CredentialsEngineImplementationTest.java
- src/test/java/nl/esciencecenter/xenon/engine/credentials/ITCredentialsEngineImplementationTest.java
- Fixed tests that needed SSH files
- Added Travis badge to README
> Travis is working

- src/integrationTest/java/nl/esciencecenter/xenon/jobs/SandboxedLocalJobIT.java
- src/main/java/nl/esciencecenter/xenon/adaptors/gridengine/GridEngineSetup.java
- src/main/java/nl/esciencecenter/xenon/adaptors/local/LocalJobs.java
- src/main/java/nl/esciencecenter/xenon/adaptors/slurm/SlurmAdaptor.java
- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshUtil.java
- src/test/java/nl/esciencecenter/xenon/adaptors/FileTestConfig.java
- src/test/java/nl/esciencecenter/xenon/adaptors/GenericTestConfig.java
- src/test/java/nl/esciencecenter/xenon/adaptors/gridengine/GridEngineSchedulerConnectionTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/gridengine/GridEngineSetupTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/local/LocalUtilsTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/slurm/SlurmJobTestConfig.java
- src/test/java/nl/esciencecenter/xenon/adaptors/ssh/SSHJobTestConfig.java
- src/test/java/nl/esciencecenter/xenon/adaptors/torque/TorqueJobTestConfig.java
- src/test/java/nl/esciencecenter/xenon/engine/AdaptorStatusImplementationTest.java
hopefully doesnt kill anything, I just followed Eclipse's hints
> removed unused imports

- src/integrationTest/docker/xenon.test.properties.docker
Travis mail fail is they take too long.
> Decreased slurm timeouts for intergration tests. 

- src/main/java/nl/esciencecenter/xenon/XenonFactory.java
changed comment about the user having to clean up their xenon instances as suggested in issue #195.
> changed comment as suggested in issue #195

- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshAdaptor.java
> Wrong type for XenonPropertyDescriptionImplementation. Fixes issue #345.

- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshAdaptor.java
Make sure the config file is also correctly read in Windows: use File.separator.Updated messages to reflect change. Meant to fix #349.
> Read config and known_hosts file in Windows

- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/ssh/SSHAgentForwardingTest.java
> Added test for SSH agent forwarding.

- .travis.yml
> Added OSX unit + local integration tests to Travis-ci

- README.md
- appveyor.yml
- gradle/license.gradle
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/GenericFileAdaptorTestParent.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/GenericScheduleJobTestParent.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/local/LocalFileAdaptorTest.java
- src/integrationTest/resources/scripts/create_symlinks.bat
- src/main/java/nl/esciencecenter/xenon/adaptors/local/LocalFileAttributes.java
- src/main/java/nl/esciencecenter/xenon/adaptors/local/LocalUtils.java
- src/main/java/nl/esciencecenter/xenon/engine/util/JobExecutor.java
- src/main/java/nl/esciencecenter/xenon/engine/util/StreamForwarder.java
- src/main/java/nl/esciencecenter/xenon/util/Utils.java
- src/test/java/nl/esciencecenter/xenon/adaptors/local/LocalDirectoryAttributeStreamTest.java
- src/test/java/nl/esciencecenter/xenon/util/RealFileUtilsTest.java
Added Xenon build to appveyor at https://ci.appveyor.com/project/NLeSC/xenon
Refs #190 
* Added badge
* push/pr hooks added 
* using appveyor.yml
* shows test results in tab
* for now only unit tests
> Appveyor 4 windows

- .travis.yml
> Fix travis stuck on apt-get install docker

- .travis.yml
- doc/adaptor/adding_adaptor.md
- src/integrationTest/docker/Dockerfile
- src/integrationTest/docker/xenon.test.properties.docker
* Replaced ant with gradle
* List steps and locations to add an adaptor
> Updated adding adaptor documentation

- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/GenericFileAdaptorTestParent.java
- src/main/java/nl/esciencecenter/xenon/adaptors/generic/DirectoryStreamBase.java
- src/main/java/nl/esciencecenter/xenon/adaptors/gridengine/GridEngineSchedulerConnection.java
- src/main/java/nl/esciencecenter/xenon/adaptors/scripting/SchedulerConnection.java
- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/OpenSSHConfig.java
- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshFiles.java
- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshInputStream.java
- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshMultiplexedSession.java
- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshOutputStream.java
- src/main/java/nl/esciencecenter/xenon/adaptors/torque/TorqueSchedulerConnection.java
- src/main/java/nl/esciencecenter/xenon/adaptors/webdav/WebdavLocation.java
- src/main/java/nl/esciencecenter/xenon/engine/util/JobExecutor.java
- src/main/java/nl/esciencecenter/xenon/engine/util/JobQueues.java
- src/main/java/nl/esciencecenter/xenon/files/Files.java
- src/main/java/nl/esciencecenter/xenon/files/RelativePath.java
- src/main/java/nl/esciencecenter/xenon/util/Utils.java
Merging in various fixes suggested by SonarQube
> Sonarqube fixes2

- src/main/java/nl/esciencecenter/xenon/adaptors/scripting/SchedulerConnection.java
- src/main/java/nl/esciencecenter/xenon/adaptors/scripting/ScriptingParser.java
- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshInputStream.java
- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshMultiplexedSession.java
- src/main/java/nl/esciencecenter/xenon/adaptors/ssh/SshOutputStream.java
- src/main/java/nl/esciencecenter/xenon/engine/util/CommandLineUtils.java
- src/main/java/nl/esciencecenter/xenon/engine/util/JobExecutor.java
- src/main/java/nl/esciencecenter/xenon/engine/util/JobQueues.java
- src/main/java/nl/esciencecenter/xenon/util/JavaJobDescription.java
- src/main/java/nl/esciencecenter/xenon/util/Utils.java
More fixes based on SonarQube suggestions
> Sonarqube fixes3

- ROADMAP.md
(branched off of APIchange, so merging back into that)
added a couple of items from the release notes as an explicit roadmap. Fixes issue #455 (add roadmap).
> added a ROADMAP.md

- src/fixedClientEnvironmentTest/resources/run-fixed-client-environment-test.sh
Adjust docker image name of fixedClientEnvironmentTest task
Refs https://github.com/NLeSC/xenon-docker-images/issues/7
> Adjust docker image name of fixedClientEnvironmentTest task

- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/BatchProcess.java
- src/main/java/nl/esciencecenter/xenon/utils/StreamForwarder.java
- src/test/java/nl/esciencecenter/xenon/utils/StreamForwarderTest.java
> Moved StreamForwarder to public utils package

- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/ftp/FtpFileSystemDockerTest.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/ftp/FtpFileSystemTestParent.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/ftp/FtpLocationConfig.java
- src/integrationTest/resources/docker-compose/ftp.yml
- src/main/java/nl/esciencecenter/xenon/adaptors/filesystems/ftp/FtpFileAdaptor.java
Adds integration test basis for FTP adaptor
> Ftp integration test

- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/FileSystemTestParent.java
- src/main/java/nl/esciencecenter/xenon/filesystems/CopyMode.java
- src/main/java/nl/esciencecenter/xenon/filesystems/FileSystem.java
Fixes behaviour and tests for recursive copy modes
> Copyrecursivemodereplace

- src/fixedClientEnvironmentTest/java/nl/esciencecenter/xenon/adaptors/filesystems/local/LocalFileSystemTest.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/FileSystemTestParent.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/LocationConfig.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/ftp/FtpFileSystemDockerTest.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/sftp/SftpFileSystemDockerTest.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/webdav/WebdavFileSystemDockerTest.java
- src/main/java/nl/esciencecenter/xenon/adaptors/filesystems/local/LocalFileAdaptor.java
Added test for FileSystem.getEntryPath()
> File adaptor returns user working directory as entryPath

- .gitignore
- CHANGELOG.md
- build.gradle
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/FileSystemTestParent.java
- src/main/java/nl/esciencecenter/xenon/adaptors/filesystems/FileAdaptor.java
- src/main/java/nl/esciencecenter/xenon/adaptors/filesystems/PathAttributesImplementation.java
- src/main/java/nl/esciencecenter/xenon/adaptors/filesystems/ftp/FtpFileAdaptor.java
- src/main/java/nl/esciencecenter/xenon/adaptors/filesystems/ftp/FtpFileSystem.java
- src/main/java/nl/esciencecenter/xenon/adaptors/filesystems/webdav/WebdavFileAdaptor.java
- src/main/java/nl/esciencecenter/xenon/adaptors/filesystems/webdav/WebdavFileSystem.java
- src/main/java/nl/esciencecenter/xenon/filesystems/FileSystem.java
Replaced jackrabbit with sardine
Fixed connection check in FTP
> New webdav

- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/webdav/WebdavFileSystemTestParent.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineSchedulerAdaptor.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/slurm/SlurmSchedulerAdaptor.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/torque/TorqueSchedulerAdaptor.java
these texts end up in the help for xenon-cli
> Xenon cli issue36

- src/main/java/nl/esciencecenter/xenon/filesystems/Path.java
- src/test/java/nl/esciencecenter/xenon/filesystems/PathTest.java
Also added more tests and renamed tests some tests so they are more descriptive.
> Path forgot its absoluteness in getName(), normalize() 

- .travis.yml
- TESTING.md
- appveyor.yml
- src/fixedClientEnvironmentTest/java/nl/esciencecenter/xenon/adaptors/filesystems/local/LocalFileSystemTest.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/filesystems/FileSystemTestParent.java
- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/schedulers/SchedulerTestParent.java
- src/liveTest/java/nl/esciencecenter/xenon/adaptors/Utils.java
- src/liveTest/java/nl/esciencecenter/xenon/adaptors/filesystems/FileSystemTest.java
- src/liveTest/java/nl/esciencecenter/xenon/adaptors/filesystems/LiveLocationConfig.java
- src/liveTest/java/nl/esciencecenter/xenon/adaptors/schedulers/LiveLocationConfig.java
- src/liveTest/java/nl/esciencecenter/xenon/adaptors/schedulers/SchedulerTest.java
- src/liveTest/resources/scripts/create_symlinks.bat
- src/main/java/nl/esciencecenter/xenon/adaptors/filesystems/local/LocalFileAdaptor.java
- src/main/java/nl/esciencecenter/xenon/adaptors/filesystems/local/LocalFileSystem.java
- src/main/java/nl/esciencecenter/xenon/filesystems/Path.java
- src/main/java/nl/esciencecenter/xenon/utils/LocalFileSystemUtils.java
Fixed several windows related issues
> Windows live tests

- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/JobExecutor.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/JobStatusImplementation.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/QueueStatusImplementation.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/ScriptingScheduler.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineScheduler.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineUtils.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/slurm/SlurmUtils.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/torque/TorqueScheduler.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/torque/TorqueUtils.java
- src/main/java/nl/esciencecenter/xenon/filesystems/CopyStatus.java
- src/main/java/nl/esciencecenter/xenon/schedulers/JobStatus.java
- src/main/java/nl/esciencecenter/xenon/schedulers/QueueStatus.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/JobStatusImplementationTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/MockScheduler.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/QueueStatusImplementationTest.java
Also standardizes to XenonException instead of Exception in getException.
> Fixes #543 and #542

- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/JobStatusImplementation.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/QueueStatusImplementation.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/torque/TorqueScheduler.java
- src/main/java/nl/esciencecenter/xenon/schedulers/JobStatus.java
- src/main/java/nl/esciencecenter/xenon/schedulers/QueueStatus.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/JobStatusImplementationTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/QueueStatusImplementationTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineUtilsTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/slurm/SlurmUtilsTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/torque/TorqueUtilsTest.java
should fix the longlived typo as found by Joris. I still have an error when I run ``./gradlew integrationTest`` locally, but it does not seem to be caused by any changes I made in this PR.
update: interestingly, the travis result is green.
> fixes issue #238

- src/main/java/nl/esciencecenter/xenon/utils/JavaJobDescription.java
- src/test/java/nl/esciencecenter/xenon/utils/JavaJobDescriptionTest.java
Also fixes jitpack build failure.
> Java job description tests

- README.md
added rsd badge to increase outside linking to Research Software Directory to improve search engine ranking
> Jspaaks rsdbadge

- src/integrationTest/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridengineSchedulerDockerTest.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineSetup.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineUtils.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/ParallelEnvironmentInfo.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineSetupTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineUtilsTest.java
- src/test/java/nl/esciencecenter/xenon/filesystems/PathTest.java
- src/testApi/java/nl/esciencecenter/xenon/adaptors/schedulers/SchedulerLocationConfig.java
- src/testApi/java/nl/esciencecenter/xenon/adaptors/schedulers/SchedulerTestParent.java
Tries to guess a parallel environment based on node count and ProcessesPerNode.
> Sge pe picker

- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/torque/TorqueUtils.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/torque/TorqueUtilsTest.java
Will fix #628 when this PR and PR #631 is merged.
> Removed JOB_OPTION_RESOURCES from torque

- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/ScriptingUtils.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/at/AtUtils.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineScheduler.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineUtils.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/slurm/SlurmScheduler.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/slurm/SlurmUtils.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/torque/TorqueScheduler.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/torque/TorqueUtils.java
- src/main/java/nl/esciencecenter/xenon/schedulers/JobDescription.java
- src/main/java/nl/esciencecenter/xenon/utils/JavaJobDescription.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/ScriptingUtilsTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/gridengine/GridEngineUtilsTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/slurm/SlurmUtilsTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/torque/TorqueUtilsTest.java
- src/test/java/nl/esciencecenter/xenon/schedulers/JobDescriptionTest.java
- src/test/java/nl/esciencecenter/xenon/utils/JavaJobDescriptionTest.java
> Removed JobOptions from JobDescription

- build.gradle
- gradle/common.gradle
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/JobQueueScheduler.java
- src/main/java/nl/esciencecenter/xenon/adaptors/shared/ssh/SSHConnection.java
- src/main/java/nl/esciencecenter/xenon/adaptors/shared/ssh/SSHUtil.java
- src/main/java/nl/esciencecenter/xenon/filesystems/FileSystem.java
- src/main/java/nl/esciencecenter/xenon/utils/DaemonThreadFactory.java
- src/test/java/nl/esciencecenter/xenon/adaptors/filesystems/sftp/MockSSHConnection.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/JobQueueSchedulerTest.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/ssh/MockSSHClient.java
Added a proper shutdown of the `SshClient` in `SSHConnection`. This prevents the JVM from hanging for about a minute on application shutdown.
> Named pool threads

- README.md
- TESTING.md
- gradle/test.gradle
- src/fixedClientEnvironmentTest/resources/run-fixed-client-environment-test.sh
- src/integrationTest/resources/docker-compose/ftp.yml
- src/integrationTest/resources/docker-compose/gridengine-6.2.yml
- src/integrationTest/resources/docker-compose/openssh.yml
- src/integrationTest/resources/docker-compose/slurm-14.yml
- src/integrationTest/resources/docker-compose/slurm-15.yml
- src/integrationTest/resources/docker-compose/slurm-16.yml
- src/integrationTest/resources/docker-compose/slurm-17.yml
- src/integrationTest/resources/docker-compose/ssh-tunnel.yml
- src/integrationTest/resources/docker-compose/torque-5.0.0.yml
- src/integrationTest/resources/docker-compose/webdav.yml
Refs https://github.com/xenon-middleware/xenon-docker-images/issues/42
> Replace Docker images from `nlesc/xenon-*` to `xenonmiddlware/*`

- build.gradle
- gradle/common.gradle
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/JobExecutor.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/JobQueueScheduler.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/RemoteCommandRunner.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/at/AtScheduler.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/at/AtUtils.java
- src/main/java/nl/esciencecenter/xenon/adaptors/schedulers/local/CommandRunner.java
- src/test/java/nl/esciencecenter/xenon/adaptors/schedulers/at/AtUtilsTest.java
This PR improve the quality of the `at` adaptor and solves some testing issues due to dependencies that have changed location
> Improved at
